#pragma once

enum class TextureIdentifier {
    PLAY_BUTTON,
    SETTING_BUTTON,
    INSTRUCTION_BUTTON,
    EXIT_BUTTON,
    LEVEL1,
    TILE_SET_BLOCKS,
    TILE_SET_ENEMIES,
    TILE_SET_ITEMS,
    MARIO_N_IDLE, MARIO_N_RUN, MARIO_N_JUMP, MARIO_N_FLAGSLIP,
    MARIO_S_IDLE, MARIO_S_RUN, MARIO_S_JUMP, MARIO_S_CROUCH, MARIO_S_FLAGSLIP,
    MARIO_F_IDLE, MARIO_F_RUN, MARIO_F_JUMP, MARIO_F_CROUCH, MARIO_F_FLAGSLIP,
    MARIO_DEATH,
    LUIGI_N_IDLE, LUIGI_N_RUN, LUIGI_N_JUMP, LUIGI_N_FLAGSLIP,
    LUIGI_S_IDLE, LUIGI_S_RUN, LUIGI_S_JUMP, LUIGI_S_CROUCH, LUIGI_S_FLAGSLIP,
    LUIGI_DEATH,
    GOOMBA_RUN, GOOMBA_DIE, GOOMBA_DEATH, GOOMBA2_RUN, GOOMBA2_DIE, GOOMBA2_DEATH,
    KOOPA_GREEN_RUN, KOOPA_GREEN_SHELL, KOOPA_GREEN_WIGGLE, KOOPA_RED_RUN, KOOPA_RED_SHELL, KOOPA_RED_WIGGLE, KOOPA_BLUE_RUN, KOOPA_BLUE_SHELL, KOOPA_BLUE_WIGGLE,
    PIRANHA, PIRANHA2,
    PODOBOO, FIREBAR, BOWSER_MOVE, BOWSER_ATTACK, BOWSER_SHELL,
    BOWSER_FIRE, FIREBALL,
    COIN_EFFECT, EXPLOSION,
    MENU_BACKGROUND, LEVEL_BACKGROUND, LOGO,
    ACTIVE_BUTTON, ACTIVE_BUTTON_MEDIUM, ACTIVE_BUTTON_SMALL,
    HOVERED_BUTTON, HOVERED_BUTTON_MEDIUM, HOVERED_BUTTON_SMALL,
    INACTIVE_BUTTON, INACTIVE_BUTTON_MEDIUM, INACTIVE_BUTTON_SMALL,
    SOUND_ON, SOUND_OFF, HOME_BUTTON, NEXT, PREVIOUS, NEXT_WHITE, PREVIOUS_WHITE,
    CHAR_SELECT_BACKGROUND, Character_MARIO, Character_LUIGI, Character_POINTER,
    BRICKS_TEXTURE, CONFIRM_BOX, PREVIEW, PREVIEW2, PREVIEW3, PREVIEW4, PREVIEW5, PREVIEW6, PREVIEW7, PREVIEW8,
    INSTRUCTION1, INSTRUCTION2, INSTRUCTION3, INSTRUCTION4,INSTRUCTION5,
    INSTRUCTION6, INSTRUCTION7, INSTRUCTION8, INSTRUCTION9, INSTRUCTION10,
    KEYBOARD,
    PAL1, PAL2, PAL3, PAL4, PAL5
};

enum class FontIdentifier {
    PressStart2P,
    PixelifySans
};

enum class SoundIdentifier {
    NORMAL_JUMP, SUPER_JUMP,
    FIREBALL, KICK,
    MARIO_DEATH,
    POWER_UP, BOWSER_FIRE,
    BLOCK_BREAK, PIPE
};

enum class MusicIdentifier {
    BACKGROUND_MUSIC
};