#pragma once

enum class TextureIdentifier {
    PLAY_BUTTON,
    SETTING_BUTTON,
    INSTRUCTION_BUTTON,
    EXIT_BUTTON,
    LEVEL1,
    TILE_SET_BLOCKS,
    TILE_SET_ENEMIES,
    TILE_SET_ITEMS,
    MARIO_N_IDLE, MARIO_N_RUN, MARIO_N_JUMP,
    MARIO_S_IDLE, MARIO_S_RUN, MARIO_S_JUMP, MARIO_S_CROUCH,
    MARIO_F_IDLE, MARIO_F_RUN, MARIO_F_JUMP, MARIO_F_CROUCH,
    LUIGI_N_IDLE, LUIGI_N_RUN, LUIGI_N_JUMP,
    LUIGI_S_IDLE, LUIGI_S_RUN, LUIGI_S_JUMP, LUIGI_S_CROUCH,
    GOOMBA_RUN, GOOMBA_DIE, GOOMBA2_RUN, GOOMBA2_DIE,
    PIRANHA_MOVE, PIRANHA_ATTACK, PIRANHA2_MOVE, PIRANHA2_ATTACK,
    MENU_BACKGROUND, LEVEL_BACKGROUND, LOGO,
    ACTIVE_BUTTON, ACTIVE_BUTTON_MEDIUM, ACTIVE_BUTTON_SMALL,
    HOVERED_BUTTON, HOVERED_BUTTON_MEDIUM, HOVERED_BUTTON_SMALL,
    INACTIVE_BUTTON, INACTIVE_BUTTON_MEDIUM, INACTIVE_BUTTON_SMALL,
    SOUND_ON, SOUND_OFF, HOME_BUTTON, NEXT, PREVIOUS, NEXT_WHITE, PREVIOUS_WHITE,
    CHAR_SELECT_BACKGROUND, Character_MARIO, Character_LUIGI, Character_POINTER,
    BRICKS_TEXTURE, CONFIRM_BOX, PREVIEW,
    INSTRUCTION1, INSTRUCTION2, INSTRUCTION3, INSTRUCTION4,INSTRUCTION5,
    INSTRUCTION6, INSTRUCTION7, INSTRUCTION8, INSTRUCTION9, INSTRUCTION10,
    KEYBOARD
};

enum class FontIdentifier {
    PressStart2P,
    PixelifySans
};

enum class SoundIdentifier {

};

enum class MusicIdentifier {
    BACKGROUND_MUSIC
};